# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: ChronoplexSoftware.MyFamilyTree
PackageVersion: 16.0.1.0
PackageLocale: zh-CN
Publisher: Chronoplex Software
PublisherUrl: https://chronoplexsoftware.com/
PublisherSupportUrl: https://chronoplexsoftware.com/support/index.htm
PrivacyUrl: https://chronoplexsoftware.com/privacy/index.htm
Author: Chronoplex Software
PackageName: My Family Tree
PackageUrl: https://chronoplexsoftware.com/myfamilytree/
License: 专有软件
LicenseUrl: https://chronoplexsoftware.com/myfamilytree/eula/index.htm
Copyright: © 2010-2025 CHRONOPLEX SOFTWARE
CopyrightUrl: https://chronoplexsoftware.com/myfamilytree/eula/index.htm
ShortDescription: 使用 My Family Tree 轻松建立您的家谱。
Description: |-
  My Family Tree 经过精心设计，旨在帮助您通过一个简单直观的界面快速创建您的家谱。
  对于那些刚开始探索家族历史的人，它提供了一种简便的方式来可视化并分享您的家谱，包含每个家庭成员的照片、故事和基本信息。
  经验丰富的家谱学家会发现，该软件全面支持引文和证据，并提供使用 GEDCOM 文件格式传输数据的选项。
Tags:
- 家庭
- 家谱
- genealogy
- 谱
ManifestType: locale
ManifestVersion: 1.10.0
